name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: dumbTicketMachineTest
      id: dumbticketmachinetest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: dumbTicketMachineTest
        setup-command: ''
        command: gradle test --tests TestTicketMachine.dumbTicketMachineTest
        timeout: 10
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        DUMBTICKETMACHINETEST_RESULTS: "${{steps.dumbticketmachinetest.outputs.result}}"
      with:
        runners: dumbticketmachinetest
